<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Core\Permission;
use App\Models\Core\Role;
use Illuminate\Database\Seeder;

class PermissionsSeeder extends Seeder
{
    public function run(): void
    {
        $permissions = $this->getPermissions();

        foreach ($permissions as $module => $modulePermissions) {
            foreach ($modulePermissions as $slug => $name) {
                Permission::updateOrCreate(
                    ['slug' => $slug],
                    [
                        'name' => $name,
                        'module' => $module,
                        'description' => $name,
                    ]
                );
            }
        }

        // Create default global roles
        $this->createDefaultRoles();
    }

    protected function getPermissions(): array
    {
        return [
            'core' => [
                'core.users.view'           => 'View Users',
                'core.users.create'         => 'Create Users',
                'core.users.update'         => 'Update Users',
                'core.users.edit'           => 'Edit Users',
                'core.users.delete'         => 'Delete Users',
                'core.roles.view'           => 'View Roles',
                'core.roles.create'         => 'Create Roles',
                'core.roles.edit'           => 'Edit Roles',
                'core.roles.update'         => 'Update Roles',
                'core.roles.delete'         => 'Delete Roles',
                'core.branches.view'        => 'View Branches',
                'core.branches.create'      => 'Create Branches',
                'core.branches.update'      => 'Update Branches',
                'core.branches.delete'      => 'Delete Branches',
                'core.settings.view'        => 'View Settings',
                'core.settings.update'      => 'Update Settings',
                'core.settings.edit'        => 'Edit Settings',
                'core.change-freeze.manage' => 'Manage Change Freeze Periods',
                'core.feature-flags.manage' => 'Manage Feature Flags',
                'modules.manage'            => 'Manage Modules',
                'features.view'             => 'View Feature Flags',
            ],
            'accounting' => [
                'accounting.accounts.view'                      => 'View Chart of Accounts',
                'accounting.accounts.create'                    => 'Create Accounts',
                'accounting.accounts.update'                    => 'Update Accounts',
                'accounting.accounts.delete'                    => 'Delete Accounts',
                'accounting.fiscal-years.view'                  => 'View Fiscal Years',
                'accounting.fiscal-years.create'                => 'Create Fiscal Years',
                'accounting.fiscal-years.update'                => 'Update Fiscal Years',
                'accounting.fiscal-years.delete'                => 'Delete Fiscal Years',
                'accounting.fiscal-years.close'                 => 'Close Fiscal Years',
                'accounting.journals.view'                      => 'View Journal Entries',
                'accounting.journals.create'                    => 'Create Journal Entries',
                'accounting.journals.update'                    => 'Update Journal Entries',
                'accounting.journals.delete'                    => 'Delete Journal Entries',
                'accounting.journals.post'                      => 'Post Journal Entries',
                'accounting.journals.void'                      => 'Void Journal Entries',
                'accounting.journals.reverse'                   => 'Reverse Journal Entries',
                'accounting.reports.view'                       => 'View Financial Reports',
                'accounting.bank-accounts.view'                 => 'View Bank Accounts',
                'accounting.bank-accounts.create'               => 'Create Bank Accounts',
                'accounting.bank-accounts.update'               => 'Update Bank Accounts',
                'accounting.bank-accounts.delete'               => 'Delete Bank Accounts',
                'accounting.bank-accounts.reconcile'            => 'Reconcile Bank Accounts',
                'accounting.bank-reconciliation.view'           => 'View Bank Reconciliation',
                'accounting.bank-reconciliation.create'         => 'Create Bank Reconciliation',
                'accounting.bank-reconciliation.update'         => 'Update Bank Reconciliation',
                'accounting.bank-reconciliation.import'         => 'Import Bank Statements',
                'accounting.bank-reconciliation.complete'       => 'Complete Bank Reconciliation',
                'accounting.loans.view'                         => 'View Loans',
                'accounting.loans.create'                       => 'Create Loans',
                'accounting.loans.update'                       => 'Update Loans',
                'accounting.loans.approve'                      => 'Approve Loans',
                'accounting.loans.payment'                      => 'Record Loan Payments',
                'accounting.loans.close'                        => 'Close Loans',
                'accounting.asset_categories.view'              => 'View Asset Categories',
                'accounting.asset_categories.create'            => 'Create Asset Categories',
                'accounting.asset_categories.update'            => 'Update Asset Categories',
                'accounting.asset_categories.delete'            => 'Delete Asset Categories',
                'accounting.assets.view'                        => 'View Fixed Assets',
                'accounting.assets.create'                      => 'Create Fixed Assets',
                'accounting.assets.update'                      => 'Update Fixed Assets',
                'accounting.assets.delete'                      => 'Delete Fixed Assets',
                'accounting.assets.dispose'                     => 'Dispose Fixed Assets',
                'accounting.depreciation_runs.view'             => 'View Depreciation Runs',
                'accounting.depreciation_runs.create'           => 'Create Depreciation Runs',
                'accounting.depreciation_runs.post'             => 'Post Depreciation Runs',
                'accounting.controlling.cost-center.view'       => 'View Cost Centers',
                'accounting.controlling.cost-center.create'     => 'Create Cost Centers',
                'accounting.controlling.cost-center.update'     => 'Update Cost Centers',
                'accounting.controlling.cost-center.delete'     => 'Delete Cost Centers',
                'accounting.controlling.cost-center.assign'     => 'Assign Cost Centers',
                'accounting.controlling.profit-center.view'     => 'View Profit Centers',
                'accounting.controlling.profit-center.create'   => 'Create Profit Centers',
                'accounting.controlling.profit-center.update'   => 'Update Profit Centers',
                'accounting.controlling.profit-center.delete'   => 'Delete Profit Centers',
                'accounting.controlling.allocation.view'        => 'View Cost Allocations',
                'accounting.controlling.allocation.create'      => 'Create Cost Allocations',
                'accounting.controlling.allocation.post'        => 'Post Cost Allocations',
                'accounting.cash-flow.view'                     => 'View Cash Flow',
                'accounting.cash-flow.manage'                   => 'Manage Cash Flow Forecasts',
                'accounting.cash-flow.generate'                 => 'Generate Cash Flow Reports',
                'accounting.dunning.view'                       => 'View Dunning',
                'accounting.dunning.configure'                  => 'Configure Dunning Rules',
                'accounting.dunning.run'                        => 'Run Dunning',
                'accounting.dunning.send'                       => 'Send Dunning Notices',
                'accounting.dunning.block'                      => 'Block Dunning',
                'accounting.credit.view'                        => 'View Credit Limits',
                'accounting.credit.manage'                      => 'Manage Credit Limits',
                'accounting.credit.hold'                        => 'Place Credit Holds',
                'accounting.petty-cash.view'                    => 'View Petty Cash',
                'accounting.petty-cash.create'                  => 'Create Petty Cash Transactions',
                'accounting.petty-cash.approve'                 => 'Approve Petty Cash',
                'accounting.petty-cash.post'                    => 'Post Petty Cash',
                'accounting.petty-cash.manage'                  => 'Manage Petty Cash Funds',
                'accounting.transfers.view'                     => 'View Inter-Company Transfers',
                'accounting.transfers.create'                   => 'Create Inter-Company Transfers',
                'accounting.transfers.approve'                  => 'Approve Inter-Company Transfers',
                'accounting.transfers.complete'                 => 'Complete Inter-Company Transfers',
                'accounting.consolidation.view'                 => 'View Consolidation',
                'accounting.consolidation.create'               => 'Create Consolidation',
                'accounting.consolidation.edit'                 => 'Edit Consolidation',
                'accounting.consolidation.complete'             => 'Complete Consolidation',
                'accounting.consolidation.delete'               => 'Delete Consolidation',
                'accounting.period-lock.manage'                 => 'Manage Period Locks',
            ],
            'inventory' => [
                'inventory.products.view'               => 'View Products',
                'inventory.products.create'             => 'Create Products',
                'inventory.products.edit'               => 'Edit Products',
                'inventory.products.update'             => 'Update Products',
                'inventory.products.delete'             => 'Delete Products',
                'inventory.categories.view'             => 'View Product Categories',
                'inventory.categories.create'           => 'Create Product Categories',
                'inventory.categories.edit'             => 'Edit Product Categories',
                'inventory.categories.delete'           => 'Delete Product Categories',
                'inventory.warehouses.view'             => 'View Warehouses',
                'inventory.warehouses.create'           => 'Create Warehouses',
                'inventory.warehouses.edit'             => 'Edit Warehouses',
                'inventory.warehouses.delete'           => 'Delete Warehouses',
                'inventory.warehouses.manage'           => 'Manage Warehouses',
                'inventory.stock.view'                  => 'View Stock',
                'inventory.stock.adjust'                => 'Adjust Stock',
                'inventory.stock.transfer'              => 'Transfer Stock',
                'inventory.stock.reserve'               => 'Reserve Stock',
                'inventory.stock-adjustments.view'      => 'View Stock Adjustments',
                'inventory.stock-adjustments.create'    => 'Create Stock Adjustments',
                'inventory.stock-adjustments.edit'      => 'Edit Stock Adjustments',
                'inventory.stock-adjustments.post'      => 'Post Stock Adjustments',
                'inventory.stock-transfers.view'        => 'View Stock Transfers',
                'inventory.stock-transfers.create'      => 'Create Stock Transfers',
                'inventory.stock-transfers.edit'        => 'Edit Stock Transfers',
                'inventory.stock-transfers.ship'        => 'Ship Stock Transfers',
                'inventory.stock-transfers.receive'     => 'Receive Stock Transfers',
                'inventory.warehouse-mgmt.view'         => 'View Warehouse Management',
                'inventory.warehouse-mgmt.manage'       => 'Manage Warehouse Tasks',
                'inventory.warehouse-mgmt.pick'         => 'Pick Warehouse Orders',
                'inventory.reports.view'                => 'View Inventory Reports',
            ],
            'sales' => [
                'sales.customers.view'                  => 'View Customers',
                'sales.customers.create'                => 'Create Customers',
                'sales.customers.update'                => 'Update Customers',
                'sales.customers.delete'                => 'Delete Customers',
                'sales.contacts.view'                   => 'View Contacts',
                'sales.contacts.create'                 => 'Create Contacts',
                'sales.contacts.edit'                   => 'Edit Contacts',
                'sales.contacts.delete'                 => 'Delete Contacts',
                'sales.quotations.view'                 => 'View Quotations',
                'sales.quotations.create'               => 'Create Quotations',
                'sales.quotations.update'               => 'Update Quotations',
                'sales.quotations.edit'                 => 'Edit Quotations',
                'sales.quotations.delete'               => 'Delete Quotations',
                'sales.quotations.send'                 => 'Send Quotations',
                'sales.quotations.convert'              => 'Convert Quotations',
                'sales.orders.view'                     => 'View Sales Orders',
                'sales.orders.create'                   => 'Create Sales Orders',
                'sales.orders.update'                   => 'Update Sales Orders',
                'sales.orders.edit'                     => 'Edit Sales Orders',
                'sales.orders.delete'                   => 'Delete Sales Orders',
                'sales.orders.confirm'                  => 'Confirm Sales Orders',
                'sales.orders.cancel'                   => 'Cancel Sales Orders',
                'sales.orders.convert'                  => 'Convert Sales Orders',
                'sales.invoices.view'                   => 'View Invoices',
                'sales.invoices.create'                 => 'Create Invoices',
                'sales.invoices.update'                 => 'Update Invoices',
                'sales.invoices.edit'                   => 'Edit Invoices',
                'sales.invoices.delete'                 => 'Delete Invoices',
                'sales.invoices.void'                   => 'Void Invoices',
                'sales.invoices.send'                   => 'Send Invoices',
                'sales.invoices.credit-note'            => 'Create Credit Notes from Invoice',
                'sales.payments.view'                   => 'View Payments',
                'sales.payments.create'                 => 'Record Payments',
                'sales.payments.complete'               => 'Complete Payments',
                'sales.payments.allocate'               => 'Allocate Payments',
                'sales.payments.void'                   => 'Void Payments',
                'sales.payments.delete'                 => 'Delete Payments',
                'sales.returns.view'                    => 'View Sales Returns',
                'sales.returns.create'                  => 'Create Sales Returns',
                'sales.returns.approve'                 => 'Approve Sales Returns',
                'sales.returns.receive'                 => 'Receive Returned Items',
                'sales.returns.inspect'                 => 'Inspect Returned Items',
                'sales.returns.resolve'                 => 'Resolve Sales Returns',
                'sales.returns.exchange'                => 'Process Exchange Orders',
                'sales.credit-notes.view'               => 'View Credit Notes',
                'sales.credit-notes.create'             => 'Create Credit Notes',
                'sales.credit-notes.update'             => 'Update Credit Notes',
                'sales.credit-notes.delete'             => 'Delete Credit Notes',
                'sales.credit-notes.apply'              => 'Apply Credit Notes',
                'sales.credit-notes.approve'            => 'Approve Credit Notes',
                'sales.credit-notes.void'               => 'Void Credit Notes',
                'sales.refunds.view'                    => 'View Refunds',
                'sales.refunds.create'                  => 'Create Refunds',
                'sales.refunds.approve'                 => 'Approve Refunds',
                'sales.refunds.process'                 => 'Process Refunds',
                'sales.refunds.cancel'                  => 'Cancel Refunds',
                'sales.shipments.view'                  => 'View Shipments',
                'sales.shipments.create'                => 'Create Shipments',
                'sales.shipments.update'                => 'Update Shipments',
                'sales.promotions.view'                 => 'View Promotions',
                'sales.promotions.create'               => 'Create Promotions',
                'sales.promotions.update'               => 'Update Promotions',
                'sales.promotions.edit'                 => 'Edit Promotions',
                'sales.promotions.delete'               => 'Delete Promotions',
                'sales.wallets.view'                    => 'View Customer Wallets',
                'sales.wallets.credit'                  => 'Credit Customer Wallets',
                'sales.wallets.debit'                   => 'Debit Customer Wallets',
                'sales.wallets.adjust'                  => 'Adjust Wallet Balance',
                'sales.customer-advances.view'          => 'View Customer Advances',
                'sales.customer-advances.create'        => 'Create Customer Advances',
                'sales.customer-advances.apply'         => 'Apply Customer Advances',
                'sales.customer-advances.refund'        => 'Refund Customer Advances',
                'sales.customer-advances.delete'        => 'Delete Customer Advances',
                'sales.price-lists.view'                => 'View Price Lists',
                'sales.price-lists.manage'              => 'Manage Price Lists',
                'sales.consignment.view'                => 'View Consignment',
                'sales.consignment.manage'              => 'Manage Consignment',
                'sales.atp.check'                       => 'Check Available to Promise',
                'sales.customer-material-infos.view'    => 'View Customer Material Info',
                'sales.customer-material-infos.create'  => 'Create Customer Material Info',
                'sales.customer-material-infos.edit'    => 'Edit Customer Material Info',
                'sales.customer-material-infos.delete'  => 'Delete Customer Material Info',
                'sales.delivery-split-rules.view'       => 'View Delivery Split Rules',
                'sales.delivery-split-rules.create'     => 'Create Delivery Split Rules',
                'sales.delivery-split-rules.edit'       => 'Edit Delivery Split Rules',
                'sales.delivery-split-rules.delete'     => 'Delete Delivery Split Rules',
                'sales.output-types.view'               => 'View Output Types',
                'sales.output-types.create'             => 'Create Output Types',
                'sales.output-types.edit'               => 'Edit Output Types',
                'sales.output-types.delete'             => 'Delete Output Types',
                'sales.reports.view'                    => 'View Sales Reports',
            ],
            'purchase' => [
                'purchase.suppliers.view'           => 'View Suppliers',
                'purchase.suppliers.create'         => 'Create Suppliers',
                'purchase.suppliers.update'         => 'Update Suppliers',
                'purchase.suppliers.edit'           => 'Edit Suppliers',
                'purchase.suppliers.delete'         => 'Delete Suppliers',
                'purchase.orders.view'              => 'View Purchase Orders',
                'purchase.orders.create'            => 'Create Purchase Orders',
                'purchase.orders.update'            => 'Update Purchase Orders',
                'purchase.orders.edit'              => 'Edit Purchase Orders',
                'purchase.orders.delete'            => 'Delete Purchase Orders',
                'purchase.orders.send'              => 'Send Purchase Orders to Supplier',
                'purchase.orders.confirm'           => 'Confirm Purchase Orders',
                'purchase.orders.receive'           => 'Receive Purchase Orders',
                'purchase.orders.cancel'            => 'Cancel Purchase Orders',
                'purchase.bills.view'               => 'View Bills',
                'purchase.bills.create'             => 'Create Bills',
                'purchase.bills.update'             => 'Update Bills',
                'purchase.bills.edit'               => 'Edit Bills',
                'purchase.bills.delete'             => 'Delete Bills',
                'purchase.bills.approve'            => 'Approve Bills',
                'purchase.bills.void'               => 'Void Bills',
                'purchase.payments.view'            => 'View Payments',
                'purchase.payments.create'          => 'Make Payments',
                'purchase.payments.allocate'        => 'Allocate Payments to Bills',
                'purchase.payments.complete'        => 'Complete Payments',
                'purchase.payments.void'            => 'Void Payments',
                'purchase.payments.delete'          => 'Delete Payments',
                'purchase.rfq.view'                 => 'View RFQs',
                'purchase.rfq.create'               => 'Create RFQs',
                'purchase.rfq.edit'                 => 'Edit RFQs',
                'purchase.rfq.send'                 => 'Send RFQs to Vendors',
                'purchase.rfq.quote'                => 'Enter Vendor Quotes',
                'purchase.rfq.award'                => 'Award RFQs',
                'purchase.rfq.convert'              => 'Convert RFQ to PO',
                'purchase.gr.view'                  => 'View Goods Receipts',
                'purchase.gr.create'                => 'Create Goods Receipts',
                'purchase.gr.post'                  => 'Post Goods Receipts',
                'purchase.gr.reverse'               => 'Reverse Goods Receipts',
                'purchase.contracts.view'           => 'View Vendor Contracts',
                'purchase.contracts.create'         => 'Create Vendor Contracts',
                'purchase.contracts.edit'           => 'Edit Vendor Contracts',
                'purchase.contracts.delete'         => 'Delete Vendor Contracts',
                'purchase.contracts.activate'       => 'Activate Vendor Contracts',
                'purchase.contracts.terminate'      => 'Terminate Vendor Contracts',
                'purchase.contracts.manage'         => 'Manage Vendor Contracts',
                'purchase.contracts.release'        => 'Release Vendor Contracts',
                'purchase.vendor-advances.view'     => 'View Vendor Advances',
                'purchase.vendor-advances.create'   => 'Create Vendor Advances',
                'purchase.vendor-advances.approve'  => 'Approve Vendor Advances',
                'purchase.vendor-advances.pay'      => 'Pay Vendor Advances',
                'purchase.vendor-advances.clear'    => 'Clear Vendor Advances',
            ],
            'hr' => [
                'hr.employees.view'                     => 'View Employees',
                'hr.employees.create'                   => 'Create Employees',
                'hr.employees.update'                   => 'Update Employees',
                'hr.employees.edit'                     => 'Edit Employees',
                'hr.employees.delete'                   => 'Delete Employees',
                'hr.employees.salary'                   => 'Manage Employee Salary',
                'hr.employees.terminate'                => 'Terminate Employees',
                'hr.attendance.view'                    => 'View Attendance',
                'hr.attendance.manage'                  => 'Manage Attendance',
                'hr.leave.view'                         => 'View Leave',
                'hr.leave.create'                       => 'Apply for Leave',
                'hr.leave.manage'                       => 'Manage Leave',
                'hr.leave.approve'                      => 'Approve Leave Requests',
                'hr.payroll.view'                       => 'View Payroll',
                'hr.payroll.create'                     => 'Create Payroll Period',
                'hr.payroll.generate'                   => 'Generate Payslips',
                'hr.payroll.process'                    => 'Process Payroll',
                'hr.payroll.approve'                    => 'Approve Payroll',
                'hr.payroll.close'                      => 'Close Payroll Period',
                'hr.payroll.pay'                        => 'Mark Payslips as Paid',
                'hr.departments.view'                   => 'View Departments',
                'hr.departments.create'                 => 'Create Departments',
                'hr.departments.edit'                   => 'Edit Departments',
                'hr.departments.delete'                 => 'Delete Departments',
                'hr.designations.view'                  => 'View Designations',
                'hr.designations.create'                => 'Create Designations',
                'hr.designations.edit'                  => 'Edit Designations',
                'hr.designations.delete'                => 'Delete Designations',
                'hr.dashboard.view'                     => 'View HR Dashboard',
                'hr.reports.view'                       => 'View HR Reports',
                'hr.eosb.view'                          => 'View EOSB/Gratuity',
                'hr.eosb.manage'                        => 'Manage EOSB/Gratuity',
                'hr.gosi.view'                          => 'View GOSI Contributions',
                'hr.gosi.manage'                        => 'Manage GOSI Contributions',
                'hr.social-insurance.view'              => 'View Social Insurance',
                'hr.social-insurance.manage'            => 'Manage Social Insurance',
                'hr.benefits.view'                      => 'View Employee Benefits',
                'hr.benefits.manage'                    => 'Manage Employee Benefits',
                'hr.shifts.view'                        => 'View Shifts',
                'hr.shifts.manage'                      => 'Manage Shifts',
                'hr.shifts.request-swap'                => 'Request Shift Swap',
                'hr.succession.view'                    => 'View Succession Plans',
                'hr.succession.manage'                  => 'Manage Succession Plans',
                'hr.performance.cycles.view'            => 'View Performance Cycles',
                'hr.performance.cycles.create'          => 'Create Performance Cycles',
                'hr.performance.cycles.edit'            => 'Edit Performance Cycles',
                'hr.performance.cycles.manage'          => 'Manage Performance Cycles',
                'hr.performance.goals.view'             => 'View Performance Goals',
                'hr.performance.goals.create'           => 'Create Performance Goals',
                'hr.performance.goals.edit'             => 'Edit Performance Goals',
                'hr.performance.goals.delete'           => 'Delete Performance Goals',
                'hr.performance.goals.update-progress'  => 'Update Goal Progress',
                'hr.performance.templates.view'         => 'View Appraisal Templates',
                'hr.performance.templates.create'       => 'Create Appraisal Templates',
                'hr.performance.templates.edit'         => 'Edit Appraisal Templates',
                'hr.performance.templates.delete'       => 'Delete Appraisal Templates',
                'hr.performance.appraisals.view'        => 'View Appraisals',
                'hr.performance.appraisals.self-review' => 'Submit Self Review',
                'hr.performance.appraisals.manager-review' => 'Submit Manager Review',
                'hr.performance.appraisals.acknowledge' => 'Acknowledge Appraisal',
                'hr.recruitment.view'                   => 'View Recruitment',
                'hr.recruitment.create'                 => 'Create Job Postings',
                'hr.recruitment.edit'                   => 'Edit Job Postings',
                'hr.recruitment.delete'                 => 'Delete Job Postings',
                'hr.recruitment.publish'                => 'Publish Job Postings',
                'hr.recruitment.applications.create'    => 'Create Job Applications',
                'hr.recruitment.interviews.create'      => 'Schedule Interviews',
                'hr.recruitment.interviews.edit'        => 'Edit Interviews',
                'hr.recruitment.offers.create'          => 'Create Job Offers',
                'hr.recruitment.offers.manage'          => 'Manage Job Offers',
                'hr.recruitment.offers.send'            => 'Send Job Offers',
                'hr.recruitment.convert'                => 'Convert Candidate to Employee',
                'hr.training.view'                      => 'View Training',
                'hr.training.manage'                    => 'Manage Training',
                'hr.training.reports'                   => 'View Training Reports',
            ],
            'crm' => [
                'crm.leads.view'            => 'View Leads',
                'crm.leads.create'          => 'Create Leads',
                'crm.leads.update'          => 'Update Leads',
                'crm.leads.edit'            => 'Edit Leads',
                'crm.leads.delete'          => 'Delete Leads',
                'crm.leads.convert'         => 'Convert Leads',
                'crm.opportunities.view'    => 'View Opportunities',
                'crm.opportunities.create'  => 'Create Opportunities',
                'crm.opportunities.update'  => 'Update Opportunities',
                'crm.opportunities.edit'    => 'Edit Opportunities',
                'crm.opportunities.delete'  => 'Delete Opportunities',
                'crm.opportunities.win'     => 'Mark Opportunities as Won',
                'crm.opportunities.lose'    => 'Mark Opportunities as Lost',
                'crm.activities.view'       => 'View CRM Activities',
                'crm.activities.create'     => 'Create CRM Activities',
                'crm.activities.edit'       => 'Edit CRM Activities',
                'crm.activities.complete'   => 'Complete CRM Activities',
                'crm.territories.view'      => 'View Territories',
                'crm.territories.manage'    => 'Manage Territories',
            ],
            'manufacturing' => [
                'manufacturing.bom.view'                => 'View Bill of Materials',
                'manufacturing.bom.create'              => 'Create Bill of Materials',
                'manufacturing.bom.update'              => 'Update Bill of Materials',
                'manufacturing.bom.edit'                => 'Edit Bill of Materials',
                'manufacturing.bom.delete'              => 'Delete Bill of Materials',
                'manufacturing.workorders.view'         => 'View Work Orders',
                'manufacturing.workorders.create'       => 'Create Work Orders',
                'manufacturing.workorders.update'       => 'Update Work Orders',
                'manufacturing.workorders.edit'         => 'Edit Work Orders',
                'manufacturing.workorders.delete'       => 'Delete Work Orders',
                'manufacturing.workorders.start'        => 'Start Work Orders',
                'manufacturing.workorders.complete'     => 'Complete Work Orders',
                'manufacturing.workorders.cancel'       => 'Cancel Work Orders',
                'manufacturing.workorders.produce'      => 'Record Production',
                'manufacturing.quality.view'            => 'View Quality',
                'manufacturing.quality.create'          => 'Create Quality Records',
                'manufacturing.quality.edit'            => 'Edit Quality Records',
                'manufacturing.quality.delete'          => 'Delete Quality Records',
                'manufacturing.quality.inspect'         => 'Perform Quality Inspections',
                'manufacturing.quality.resolve'         => 'Resolve Quality Issues',
                'manufacturing.mrp.view'                => 'View MRP',
                'manufacturing.mrp.run'                 => 'Run MRP',
                'manufacturing.mrp.edit'                => 'Edit MRP Plans',
                'manufacturing.mrp.delete'              => 'Delete MRP Plans',
                'manufacturing.capacity.view'           => 'View Capacity Planning',
                'manufacturing.capacity.create'         => 'Create Capacity Records',
                'manufacturing.capacity.edit'           => 'Edit Capacity Records',
                'manufacturing.capacity.delete'         => 'Delete Capacity Records',
                'manufacturing.costing.view'            => 'View Product Costing',
                'manufacturing.costing.create'          => 'Create Cost Versions',
                'manufacturing.costing.run'             => 'Run Cost Roll-ups',
                'manufacturing.subcontracting.view'     => 'View Subcontracting',
                'manufacturing.subcontracting.create'   => 'Create Subcontracting Orders',
                'manufacturing.subcontracting.edit'     => 'Edit Subcontracting Orders',
                'manufacturing.subcontracting.cancel'   => 'Cancel Subcontracting Orders',
                'manufacturing.subcontracting.transfer' => 'Transfer Materials for Subcontracting',
                'manufacturing.subcontracting.receive'  => 'Receive Subcontracted Goods',
                'manufacturing.subcontracting.close'    => 'Close Subcontracting Orders',
            ],
            'tax' => [
                'tax.vat.view'   => 'View VAT Compliance',
                'tax.vat.manage' => 'Manage VAT Returns',
                'tax.gst.view'   => 'View GST Compliance',
                'tax.gst.manage' => 'Manage GST Returns',
                'tax.tds.view'   => 'View TDS Compliance',
                'tax.tds.manage' => 'Manage TDS Returns',
            ],
            'compliance' => [
                'compliance.onboarding.view'   => 'View Compliance Onboarding',
                'compliance.onboarding.manage' => 'Manage Compliance Onboarding',
            ],
            'customs' => [
                'customs.tariff-codes.view'        => 'View Tariff Codes',
                'customs.tariff-codes.create'      => 'Create Tariff Codes',
                'customs.excise-categories.view'   => 'View Excise Categories',
                'customs.excise-categories.create' => 'Create Excise Categories',
                'customs.declarations.view'        => 'View Customs Declarations',
                'customs.declarations.create'      => 'Create Customs Declarations',
            ],
            'trade' => [
                'trade.landed-costs.view'          => 'View Landed Costs',
                'trade.landed-costs.create'        => 'Create Landed Costs',
                'trade.landed-costs.edit'          => 'Edit Landed Costs',
                'trade.landed-costs.post'          => 'Post Landed Costs',
                'trade.landed-costs.delete'        => 'Delete Landed Costs',
                'trade.letters-of-credit.view'     => 'View Letters of Credit',
                'trade.letters-of-credit.create'   => 'Create Letters of Credit',
                'trade.letters-of-credit.edit'     => 'Edit Letters of Credit',
                'trade.letters-of-credit.issue'    => 'Issue Letters of Credit',
                'trade.letters-of-credit.utilize'  => 'Utilize Letters of Credit',
                'trade.letters-of-credit.delete'   => 'Delete Letters of Credit',
                'trade.shipments.view'             => 'View Trade Shipments',
                'trade.shipments.create'           => 'Create Trade Shipments',
                'trade.shipments.edit'             => 'Edit Trade Shipments',
                'trade.shipments.delete'           => 'Delete Trade Shipments',
                'trade.trade-agreements.view'      => 'View Trade Agreements',
                'trade.trade-agreements.create'    => 'Create Trade Agreements',
                'trade.trade-agreements.edit'      => 'Edit Trade Agreements',
                'trade.trade-agreements.delete'    => 'Delete Trade Agreements',
                'trade.trade-documents.view'       => 'View Trade Documents',
                'trade.trade-documents.create'     => 'Create Trade Documents',
                'trade.trade-documents.edit'       => 'Edit Trade Documents',
                'trade.trade-documents.delete'     => 'Delete Trade Documents',
            ],
            'maintenance' => [
                'maintenance.equipment-categories.view'   => 'View Equipment Categories',
                'maintenance.equipment-categories.create' => 'Create Equipment Categories',
                'maintenance.equipment-categories.edit'   => 'Edit Equipment Categories',
                'maintenance.equipment-categories.delete' => 'Delete Equipment Categories',
                'maintenance.equipment.view'              => 'View Equipment',
                'maintenance.equipment.create'            => 'Create Equipment',
                'maintenance.equipment.edit'              => 'Edit Equipment',
                'maintenance.equipment.delete'            => 'Delete Equipment',
                'maintenance.functional-locations.view'   => 'View Functional Locations',
                'maintenance.functional-locations.create' => 'Create Functional Locations',
                'maintenance.functional-locations.edit'   => 'Edit Functional Locations',
                'maintenance.functional-locations.delete' => 'Delete Functional Locations',
                'maintenance.orders.view'                 => 'View Maintenance Orders',
                'maintenance.orders.create'               => 'Create Maintenance Orders',
                'maintenance.orders.edit'                 => 'Edit Maintenance Orders',
                'maintenance.orders.delete'               => 'Delete Maintenance Orders',
                'maintenance.plans.view'                  => 'View Maintenance Plans',
                'maintenance.plans.create'                => 'Create Maintenance Plans',
                'maintenance.plans.edit'                  => 'Edit Maintenance Plans',
                'maintenance.stats.view'                  => 'View Maintenance Statistics',
            ],
            'projects' => [
                'projects.projects.view'      => 'View Projects',
                'projects.projects.create'    => 'Create Projects',
                'projects.projects.edit'      => 'Edit Projects',
                'projects.projects.delete'    => 'Delete Projects',
                'projects.wbs.view'           => 'View WBS',
                'projects.wbs.create'         => 'Create WBS',
                'projects.wbs.edit'           => 'Edit WBS',
                'projects.milestones.view'    => 'View Milestones',
                'projects.milestones.create'  => 'Create Milestones',
                'projects.milestones.edit'    => 'Edit Milestones',
                'projects.members.view'       => 'View Project Members',
                'projects.members.create'     => 'Add Project Members',
                'projects.members.delete'     => 'Remove Project Members',
                'projects.time.view'          => 'View Time Entries',
                'projects.time.create'        => 'Log Time',
                'projects.time.approve'       => 'Approve Time Entries',
                'projects.costs.view'         => 'View Project Costs',
                'projects.costs.create'       => 'Create Project Costs',
            ],
            'budget' => [
                'budget.budgets.view'    => 'View Budgets',
                'budget.budgets.create'  => 'Create Budgets',
                'budget.budgets.edit'    => 'Edit Budgets',
                'budget.budgets.approve' => 'Approve Budgets',
                'budget.budgets.delete'  => 'Delete Budgets',
            ],
            'expenses' => [
                'expenses.view'             => 'View Expenses',
                'expenses.create'           => 'Create Expenses',
                'expenses.update'           => 'Update Expenses',
                'expenses.delete'           => 'Delete Expenses',
                'expenses.submit'           => 'Submit Expenses',
                'expenses.approve'          => 'Approve Expenses',
                'expenses.categories.view'  => 'View Expense Categories',
                'expenses.categories.create'=> 'Create Expense Categories',
                'expenses.categories.update'=> 'Update Expense Categories',
                'expenses.categories.delete'=> 'Delete Expense Categories',
                'expenses.reports.view'     => 'View Expense Reports',
                'expenses.reports.create'   => 'Create Expense Reports',
                'expenses.reports.update'   => 'Update Expense Reports',
                'expenses.reports.submit'   => 'Submit Expense Reports',
                'expenses.reports.approve'  => 'Approve Expense Reports',
                'expenses.reports.reimburse'=> 'Reimburse Expense Reports',
                'expenses.budgets.view'     => 'View Expense Budgets',
                'expenses.budgets.create'   => 'Create Expense Budgets',
                'expenses.budgets.update'   => 'Update Expense Budgets',
                'expenses.budgets.delete'   => 'Delete Expense Budgets',
                'expenses.recurring.view'   => 'View Recurring Expenses',
                'expenses.recurring.create' => 'Create Recurring Expenses',
                'expenses.recurring.process'=> 'Process Recurring Expenses',
            ],
            'documents' => [
                'documents.folders.view'   => 'View Document Folders',
                'documents.folders.create' => 'Create Document Folders',
                'documents.files.view'     => 'View Documents',
                'documents.files.create'   => 'Upload Documents',
                'documents.files.delete'   => 'Delete Documents',
            ],
            'calendar' => [
                'calendar.calendars.view'   => 'View Calendars',
                'calendar.calendars.create' => 'Create Calendars',
                'calendar.events.view'      => 'View Events',
                'calendar.events.create'    => 'Create Events',
            ],
            'taskboard' => [
                'taskboard.boards.view'    => 'View Task Boards',
                'taskboard.boards.create'  => 'Create Task Boards',
                'taskboard.sprints.view'   => 'View Sprints',
                'taskboard.sprints.create' => 'Create Sprints',
                'taskboard.tasks.view'     => 'View Tasks',
                'taskboard.tasks.create'   => 'Create Tasks',
            ],
            'billing' => [
                'billing.plans.view'            => 'View Billing Plans',
                'billing.plans.create'          => 'Create Billing Plans',
                'billing.plans.update'          => 'Update Billing Plans',
                'billing.plans.delete'          => 'Delete Billing Plans',
                'billing.subscriptions.view'    => 'View Subscriptions',
                'billing.subscriptions.create'  => 'Create Subscriptions',
                'billing.subscriptions.update'  => 'Update Subscriptions',
                'billing.invoices.view'         => 'View Billing Invoices',
                'billing.invoices.pay'          => 'Pay Billing Invoices',
                'billing.usage.view'            => 'View Usage Metrics',
            ],
            'loyalty' => [
                'loyalty.programs.view'    => 'View Loyalty Programs',
                'loyalty.programs.create'  => 'Create Loyalty Programs',
                'loyalty.programs.delete'  => 'Delete Loyalty Programs',
                'loyalty.accounts.view'    => 'View Loyalty Accounts',
                'loyalty.accounts.create'  => 'Create Loyalty Accounts',
                'loyalty.rewards.view'     => 'View Rewards',
                'loyalty.rewards.create'   => 'Create Rewards',
            ],
            'automation' => [
                'automation.workflows.view'    => 'View Automation Workflows',
                'automation.workflows.create'  => 'Create Automation Workflows',
                'automation.workflows.update'  => 'Update Automation Workflows',
                'automation.approvals.view'    => 'View Approval Workflows',
                'automation.approvals.approve' => 'Approve Workflow Steps',
            ],
            'messaging' => [
                'messaging.conversations.view'   => 'View Conversations',
                'messaging.conversations.create' => 'Create Conversations',
                'messaging.messages.create'      => 'Send Messages',
            ],
            'reports' => [
                'reports.dashboard.view' => 'View Reports Dashboard',
            ],
        ];
    }

    protected function createDefaultRoles(): void
    {
        // Admin role - all permissions
        $admin = Role::updateOrCreate(
            ['slug' => 'admin', 'organization_id' => null],
            [
                'name' => 'Administrator',
                'description' => 'Full access to all features',
                'is_system' => true,
            ]
        );
        $admin->permissions()->sync(Permission::pluck('id'));

        // Manager role - most permissions except user/role management
        $manager = Role::updateOrCreate(
            ['slug' => 'manager', 'organization_id' => null],
            [
                'name' => 'Manager',
                'description' => 'Access to most features except user management',
                'is_system' => true,
            ]
        );
        $managerPermissions = Permission::whereNotIn('slug', [
            'core.users.create', 'core.users.delete',
            'core.roles.create', 'core.roles.update', 'core.roles.delete',
        ])->pluck('id');
        $manager->permissions()->sync($managerPermissions);

        // Accountant role
        $accountant = Role::updateOrCreate(
            ['slug' => 'accountant', 'organization_id' => null],
            [
                'name' => 'Accountant',
                'description' => 'Access to accounting and financial features',
                'is_system' => true,
            ]
        );
        $accountantPermissions = Permission::where('module', 'accounting')
            ->orWhere('slug', 'like', 'sales.invoices.%')
            ->orWhere('slug', 'like', 'sales.payments.%')
            ->orWhere('slug', 'like', 'purchase.bills.%')
            ->orWhere('slug', 'like', 'purchase.payments.%')
            ->pluck('id');
        $accountant->permissions()->sync($accountantPermissions);

        // Sales role
        $sales = Role::updateOrCreate(
            ['slug' => 'sales', 'organization_id' => null],
            [
                'name' => 'Sales Representative',
                'description' => 'Access to sales and customer features',
                'is_system' => true,
            ]
        );
        $salesPermissions = Permission::where('module', 'sales')
            ->orWhere('module', 'crm')
            ->orWhere('slug', 'inventory.products.view')
            ->pluck('id');
        $sales->permissions()->sync($salesPermissions);

        // Viewer role - read-only access
        $viewer = Role::updateOrCreate(
            ['slug' => 'viewer', 'organization_id' => null],
            [
                'name' => 'Viewer',
                'description' => 'Read-only access to all features',
                'is_system' => true,
            ]
        );
        $viewerPermissions = Permission::where('slug', 'like', '%.view')->pluck('id');
        $viewer->permissions()->sync($viewerPermissions);
    }
}
