<?php

declare(strict_types=1);

namespace App\Models\Tax;

use App\Models\Concerns\BelongsToOrganization;
use App\Models\Concerns\HasUuid;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * India GST e-invoice submission record (IRP / IRN).
 *
 * The Invoice Reference Number (IRN) is a 64-character SHA-256 hash
 * generated by the Invoice Registration Portal (IRP) after successful
 * submission of the e-invoice JSON.
 */
class IndiaEInvoiceSubmission extends Model
{
    use BelongsToOrganization, HasFactory, HasUuid;

    public const STATUS_PENDING   = 'pending';
    public const STATUS_SUBMITTED = 'submitted';
    public const STATUS_ACCEPTED  = 'accepted';
    public const STATUS_REJECTED  = 'rejected';
    public const STATUS_CANCELLED = 'cancelled';

    public const DOC_TYPE_INVOICE    = 'INV';
    public const DOC_TYPE_CREDIT     = 'CRN';
    public const DOC_TYPE_DEBIT      = 'DBN';

    protected $table = 'india_einvoice_submissions';

    protected $fillable = [
        'organization_id',
        'invoice_id',
        'document_number',
        'document_type',
        'document_date',
        'gstin_seller',
        'gstin_buyer',
        'seller_name',
        'buyer_name',
        'seller_state_code',
        'buyer_state_code',
        'taxable_value',
        'cgst_amount',
        'sgst_amount',
        'igst_amount',
        'cess_amount',
        'total_amount',
        'irn',
        'signed_invoice',
        'signed_qr_code',
        'einvoice_json',
        'status',
        'irp_ack_number',
        'irp_ack_date',
        'irp_response',
        'cancel_reason',
        'cancelled_at',
        'notes',
        'created_by',
    ];

    protected $casts = [
        'taxable_value'  => 'float',
        'cgst_amount'    => 'float',
        'sgst_amount'    => 'float',
        'igst_amount'    => 'float',
        'cess_amount'    => 'float',
        'total_amount'   => 'float',
        'irp_ack_date'   => 'datetime',
        'cancelled_at'   => 'datetime',
    ];

    public function isPending(): bool
    {
        return $this->status === self::STATUS_PENDING;
    }

    public function isAccepted(): bool
    {
        return $this->status === self::STATUS_ACCEPTED;
    }

    public function isCancelled(): bool
    {
        return $this->status === self::STATUS_CANCELLED;
    }
}
