<?php
// Scan all migration files in current directory
$files = glob('*.php');
sort($files);

$problemsFound = [];
$namedConstraints = [];
$autoGeneratedConstraints = [];

foreach ($files as $file) {
    $content = file_get_contents($file);
    $lines = explode("\n", $content);
    $currentTable = null;
    
    for ($lineNum = 0; $lineNum < count($lines); $lineNum++) {
        $line = $lines[$lineNum];
        
        // Track table name
        if (preg_match('/Schema::(create|table)\s*\(\s*[\'"]([^\'"]+)[\'"]/', $line, $m)) {
            $currentTable = $m[2];
        }
        
        // Look for ->unique([...]) or ->index([...]) with array columns
        if (preg_match('/\->(unique|index)\s*\(\s*\[/', $line)) {
            // Try to match the complete pattern
            if (preg_match('/\->(unique|index)\s*\(\s*\[\s*([^\]]+)\]\s*(?:,\s*[\'"]([^\'"]*)[\'"])?\s*\)/', $line, $matches)) {
                $constraint_type = $matches[1];
                $columns_str = $matches[2];
                $custom_name = isset($matches[3]) && trim($matches[3]) !== '' ? trim($matches[3]) : null;
                
                // Parse columns
                $columns_raw = preg_replace('/[\'"]/', '', $columns_str);
                $columns_raw = preg_replace('/\s+/', ' ', $columns_raw);
                $columns = array_filter(array_map('trim', explode(',', $columns_raw)));
                
                if (!empty($columns) && $currentTable) {
                    if ($custom_name === null) {
                        // Auto-generated name
                        $suffix = (strtolower($constraint_type) === 'unique') ? '_unique' : '_index';
                        $auto_name = $currentTable . '_' . implode('_', $columns) . $suffix;
                        $auto_length = strlen($auto_name);
                        
                        $autoGeneratedConstraints[] = [
                            'file' => $file,
                            'line' => $lineNum + 1,
                            'table' => $currentTable,
                            'type' => $constraint_type,
                            'columns' => $columns,
                            'auto_name' => $auto_name,
                            'length' => $auto_length
                        ];
                        
                        if ($auto_length > 64) {
                            $problemsFound[] = end($autoGeneratedConstraints);
                        }
                    } else {
                        // Named constraint
                        $namedConstraints[] = [
                            'file' => $file,
                            'line' => $lineNum + 1,
                            'table' => $currentTable,
                            'type' => $constraint_type,
                            'columns' => $columns,
                            'custom_name' => $custom_name,
                            'length' => strlen($custom_name)
                        ];
                    }
                }
            }
        }
    }
}

echo "=== PROBLEMS FOUND (auto-generated names > 64 chars) ===\n\n";
if (empty($problemsFound)) {
    echo "None found! All auto-generated index/unique constraint names are within the 64-character MySQL limit.\n";
} else {
    echo "Found " . count($problemsFound) . " problematic constraint(s):\n\n";
    foreach ($problemsFound as $problem) {
        echo "File: " . $problem['file'] . "\n";
        echo "  Line: " . $problem['line'] . "\n";
        echo "  Table: " . $problem['table'] . "\n";
        echo "  Type: " . $problem['type'] . "\n";
        echo "  Columns: " . implode(', ', $problem['columns']) . "\n";
        echo "  Auto-generated name: " . $problem['auto_name'] . "\n";
        echo "  Length: " . $problem['length'] . " (exceeds 64 by " . ($problem['length'] - 64) . ")\n";
        echo "\n";
    }
}

echo "\n=== SUMMARY ===\n";
$total = count($problemsFound) + count($namedConstraints) + count($autoGeneratedConstraints);
echo "Total multi-column unique/index constraints analyzed: " . $total . "\n";
echo "  - Auto-generated (no custom name): " . count($autoGeneratedConstraints) . "\n";
echo "  - Named (custom name provided): " . count($namedConstraints) . "\n";
echo "  - Problematic (> 64 chars auto-generated): " . count($problemsFound) . "\n";

if (!empty($namedConstraints)) {
    echo "\n=== NAMED CONSTRAINTS (custom names provided) ===\n";
    echo "Total: " . count($namedConstraints) . "\n\n";
    
    usort($namedConstraints, function($a, $b) {
        return $b['length'] - $a['length'];
    });
    
    foreach ($namedConstraints as $constraint) {
        $status = $constraint['length'] <= 64 ? 'OK' : 'LONG';
        echo "[$status] " . $constraint['file'] . ":" . $constraint['line'] . "\n";
        echo "        Table: " . $constraint['table'] . " | Type: " . $constraint['type'] . "\n";
        echo "        Columns: " . implode(', ', $constraint['columns']) . "\n";
        echo "        Custom name: \"" . $constraint['custom_name'] . "\" (" . $constraint['length'] . " chars)\n";
        echo "\n";
    }
}

// Show some examples of auto-generated constraints (longest ones)
if (!empty($autoGeneratedConstraints)) {
    echo "\n=== SAMPLE AUTO-GENERATED CONSTRAINTS (within 64 char limit) ===\n";
    echo "Showing 15 longest auto-generated names (all passing):\n\n";
    
    usort($autoGeneratedConstraints, function($a, $b) {
        return $b['length'] - $a['length'];
    });
    
    $count = 0;
    foreach ($autoGeneratedConstraints as $constraint) {
        if ($count >= 15) break;
        echo "[OK] " . $constraint['file'] . ":" . $constraint['line'] . "\n";
        echo "     Table: " . $constraint['table'] . " | Type: " . $constraint['type'] . "\n";
        echo "     Columns: " . implode(', ', $constraint['columns']) . "\n";
        echo "     Auto name: \"" . $constraint['auto_name'] . "\" (" . $constraint['length'] . " chars)\n";
        echo "\n";
        $count++;
    }
}
?>
