<?php

declare(strict_types=1);

namespace App\Services\Purchase;

use App\Models\Purchase\Bill;
use App\Models\Purchase\ErsConfiguration;
use App\Models\Purchase\ErsRun;
use App\Models\Purchase\ErsRunItem;
use App\Models\Purchase\GoodsReceipt;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Throwable;

class ErsService
{
    public function getOrCreateConfig(int $orgId, int $vendorId): ErsConfiguration
    {
        return ErsConfiguration::firstOrCreate(
            [
                'organization_id' => $orgId,
                'vendor_id'       => $vendorId,
            ],
            [
                'is_enabled'        => true,
                'auto_post'         => false,
                'tolerance_percent' => 0,
            ]
        );
    }

    public function saveConfig(int $orgId, int $vendorId, array $data): ErsConfiguration
    {
        $config = $this->getOrCreateConfig($orgId, $vendorId);
        $config->update($data);

        return $config->fresh();
    }

    public function runErs(int $orgId, ?array $vendorIds = null): ErsRun
    {
        $run = ErsRun::create([
            'organization_id' => $orgId,
            'run_date'        => today(),
            'status'          => ErsRun::STATUS_RUNNING,
            'run_by'          => Auth::id(),
        ]);

        try {
            $configQuery = ErsConfiguration::where('organization_id', $orgId)
                ->where('is_enabled', true);

            if ($vendorIds !== null) {
                $configQuery->whereIn('vendor_id', $vendorIds);
            }

            $enabledVendorIds = $configQuery->pluck('vendor_id')->toArray();

            // Find posted GRs not yet processed by ERS (no ERS run item pointing to them)
            $processedGrIds = ErsRunItem::where('organization_id', $orgId)
                ->whereIn('status', [ErsRunItem::STATUS_PROCESSED])
                ->pluck('goods_receipt_id')
                ->toArray();

            $receipts = GoodsReceipt::where('organization_id', $orgId)
                ->where('status', GoodsReceipt::STATUS_POSTED)
                ->whereIn('contact_id', $enabledVendorIds)
                ->whereNotIn('id', $processedGrIds)
                ->get();

            $processedCount = 0;
            $errorCount     = 0;

            foreach ($receipts as $receipt) {
                try {
                    $this->processGoodsReceipt($run, $receipt);
                    $processedCount++;
                } catch (Throwable $e) {
                    $errorCount++;
                    Log::error('ERS processing failed for GR #' . $receipt->id . ': ' . $e->getMessage());
                }
            }

            $run->update([
                'status'          => ErsRun::STATUS_COMPLETED,
                'processed_count' => $processedCount,
                'error_count'     => $errorCount,
                'completed_at'    => now(),
            ]);
        } catch (Throwable $e) {
            $run->update([
                'status'       => ErsRun::STATUS_FAILED,
                'completed_at' => now(),
            ]);

            Log::error('ERS run failed: ' . $e->getMessage());
        }

        return $run->fresh();
    }

    public function processGoodsReceipt(ErsRun $run, GoodsReceipt $gr): ErsRunItem
    {
        try {
            $grossAmount = $gr->getTotalCost();

            $bill = DB::transaction(function () use ($run, $gr, $grossAmount) {
                $config = ErsConfiguration::where('organization_id', $gr->organization_id)
                    ->where('vendor_id', $gr->contact_id)
                    ->first();

                $bill = Bill::create([
                    'organization_id'        => $gr->organization_id,
                    'supplier_id'            => $gr->contact_id,
                    'purchase_order_id'      => $gr->purchase_order_id,
                    'bill_type'              => Bill::TYPE_STANDARD,
                    'status'                 => ($config && $config->auto_post)
                        ? Bill::STATUS_APPROVED
                        : Bill::STATUS_DRAFT,
                    'bill_date'              => today(),
                    'due_date'               => today()->addDays(30),
                    'subtotal'               => $grossAmount,
                    'tax_amount'             => 0,
                    'total'                  => $grossAmount,
                    'notes'                  => 'Auto-generated by ERS from GR #' . $gr->gr_number,
                ]);

                return $bill;
            });

            return ErsRunItem::create([
                'organization_id' => $run->organization_id,
                'ers_run_id'      => $run->id,
                'goods_receipt_id' => $gr->id,
                'bill_id'         => $bill->id,
                'vendor_id'       => $gr->contact_id,
                'gross_amount'    => $grossAmount,
                'status'          => ErsRunItem::STATUS_PROCESSED,
            ]);
        } catch (Throwable $e) {
            return ErsRunItem::create([
                'organization_id'  => $run->organization_id,
                'ers_run_id'       => $run->id,
                'goods_receipt_id' => $gr->id,
                'vendor_id'        => $gr->contact_id,
                'gross_amount'     => 0,
                'status'           => ErsRunItem::STATUS_FAILED,
                'error_message'    => $e->getMessage(),
            ]);
        }
    }
}
